// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"

	"gopkg.in/mgo.v2/bson"
)

type Cap struct {
	ID      bson.ObjectId `json:"id" bson:"_id,omitempty"`
	Product string        `json:"product" bson:"product"`
	Desc    string        `json:"desc" bson:"desc"`
	Year    int           `json:"year" bson:"year"`
	Week    int           `json:"week" bson:"week"`
	Ctime   time.Time     `json:"ctime" bson:"ctime"`
	Utime   time.Time     `json:"utime" bson:"utime"`
}

type CapList struct {
	Code  *int   `json:"code" bson:"code"`
	Data  []*Cap `json:"data" bson:"data"`
	Count int    `json:"count" bson:"count"`
}

type CreateCapInput struct {
	Product string `json:"product" bson:"product"`
	Desc    string `json:"desc" bson:"desc"`
}

type DeleteCap struct {
	Success bool `json:"success" bson:"success"`
}

type NewTicket struct {
	Order map[string]interface{} `json:"order" bson:"order"`
}

type Ticket struct {
	ID      bson.ObjectId          `json:"id" bson:"_id,omitempty"`
	Order   map[string]interface{} `json:"order" bson:"order"`
	Week    string                 `json:"week" bson:"week"`
	Year    string                 `json:"year" bson:"year"`
	Created time.Time              `json:"created" bson:"created"`
	Updated time.Time              `json:"updated" bson:"updated"`
}

type TicketRes struct {
	Data  []*Ticket `json:"data" bson:"data"`
	Count int       `json:"count" bson:"count"`
}

type UpdateCap struct {
	Success bool `json:"success" bson:"success"`
}

type UpdateCapInput struct {
	Product string `json:"product" bson:"product"`
	Desc    string `json:"desc" bson:"desc"`
}
